# Generated by Django 2.0.3 on 2018-06-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('building_id',),
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_name', models.CharField(max_length=10)),
                ('avaliable_parking', models.IntegerField()),
                ('total_parking', models.IntegerField()),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emulators.Building')),
            ],
            options={
                'ordering': ('floor_id',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=10)),
                ('is_avaliable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position_id',),
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=10)),
                ('avaliable_parking', models.IntegerField()),
                ('total_parking', models.IntegerField()),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emulators.Floor')),
            ],
            options={
                'ordering': ('zone_id',),
            },
        ),
        migrations.AddField(
            model_name='position',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emulators.Zone'),
        ),
    ]
