# Generated by Django 2.0.3 on 2018-07-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emulators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='building_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='zone_id',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='floor_id',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
