# Generated by Django 2.0.3 on 2018-07-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=10)),
                ('is_avaliable', models.BooleanField(default=True)),
                ('zone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zones.Zone')),
            ],
            options={
                'ordering': ('position_id',),
            },
        ),
    ]
