# Generated by Django 2.0.3 on 2018-07-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_name', models.CharField(max_length=10)),
                ('avaliable_parking', models.IntegerField()),
                ('total_parking', models.IntegerField()),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildings.Building')),
            ],
            options={
                'ordering': ('floor_id',),
            },
        ),
    ]
